### ISSUE TITLE
The upstream repo is misconfigured: won't clone, incorrect support URL, and scraped and publicized a username from my private e-mail address

### ISSUE THREAD

**Issue by poikilos** [taradinoc/zilf#1]
Trying to get ZIL working leads to an endless rabbit hole due to cumulative factors below.
- After finding https://github.com/historicalsource and infocom source code being released, I am trying to run ZIL.
  - Looking for interpreters leads me to a modern ZIL game: https://github.com/daelsepara/zil-experiment
    - The URL of the game instructs me to use ZILF to convert ZIL to IF. They say to go to https://bitbucket.org/jmcgrew/zilf/wiki/Home
      - That URL says the repo moved to zilf.io
        - zilf.io forwards me to https://foss.heptapod.net/zilf/zilf/-/wikis/home
          - Your GitLab instance is misconfigured, so the clone URLs don't clone ("fatal: repository 'https://foss.heptapod.net/zilf/zilf/' not found")
            - [ ] Your GitLab instance forces me to create a password to clone even though I signed in with a bitbucket account
              - [ ] It automatically set my username to the first part of my e-mail which is private! That is not my username on BitBucket it is my private e-mail and your site shouldn't extract it and make the part before the @ my public username.
              - [ ] If you don't let people logging in via BitBucket to do anything, then don't allow it as a sign-in option (same for GitHub if you misuse my e-mail address from that in the same way you do with BitBucket).
            - There is no "Issues" link there and nothing there says to go here.
            - [ ] None of your GitLab instance's support URLs are set, so all support-type links go to gitlab.com, but the issue isn't with gitlab's software, its with your instance. The links should point to somewhere to reach the admin of foss.heptapod.net.
              - I had to find your name in the list of Wiki contributors then Google your full name to get to this normal cloneable repo with a support method. 

Conclusions:
- This has been a frustrating dead end. The only way out of the rabbit hole was to get your full name then go back to the start and Google it to get here. 
- I want my username on foss.hexapod.net changed to Poikilos or deleted immediately! I requested access to the zilf group so you can see my username there
  - **On this public issue, don't mention the username that your site scraped from my private e-mail**. Contact me at <https://expertmultimedia.com/index.php?htmlref=contact.html> if you have any questions.

**Comment by taradinoc** [comment]
That sounds frustrating. I probably need to write up some instructions for working with the ZILF source code.

A few points in response:

* If your goal is to compile some ZIL code, consider just downloading the [binaries linked from the wiki](https://foss.heptapod.net/zilf/zilf/-/wikis/Releases/0.9/Downloads) instead of building ZILF from source.

> Your GitLab instance is misconfigured, so the clone URLs don't clone ("fatal: repository 'https://foss.heptapod.net/zilf/zilf/' not found")

* The repository on foss.heptapod.net is a Mercurial repo, not a Git repo. `git clone` will indeed give you that error message, but `hg clone` ought to work fine - no login required.

> None of your GitLab instance's support URLs are set, so all support-type links go to gitlab.com

* Heptapod is a Mercurial hosting service, based on a fork of GitLab, and it looks like they haven't changed all the GitLab references yet. This would be good feedback for the [Heptapod developers](https://foss.heptapod.net/heptapod).

> I want my username on foss.hexapod.net changed to Poikilos or deleted immediately!

* `foss.heptapod.net` is a public instance, so I don't think I can do anything about that. The [administrators](https://foss.heptapod.net/heptapod/foss.heptapod.net) might be able to help you.

>  I requested access to the zilf group so you can see my username there

* Thanks. To preserve your privacy, I've declined the request. If you'd like access in the future, feel free to re-apply once you get that sorted out.

**Comment by poikilos** [comment]
Thanks for clearing things up.
